/* Generated By:JavaCC: Do not edit this line. WeightFileParserConstants.java */
package input;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface WeightFileParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ID = 5;
  /** RegularExpression Id. */
  int COMMA = 6;
  /** RegularExpression Id. */
  int RIGHTARROW = 7;
  /** RegularExpression Id. */
  int VALUE = 8;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<ID>",
    "\",\"",
    "\"->\"",
    "<VALUE>",
  };

}
